name: Command deployment script

on: 
  push:
    branches:
      - master
jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repo
       uses: actions/checkout@v3

     - name: NJS setup
       uses: actions/setup-node@v3
       with:
        node-version: '18'
     
  
    
